### ISSUE TITLE
✅ 프로필 제작 플로우 화면 작업

### ISSUE THREAD

**Issue by moondev03** [Prography-RoomE/roome_aos#11]
### 💼 작업 설명

프로필 제작 플로우 화면 작업 (API 연결 x)

<br>

### ✅ To-do

- [x] 가입 인사 페이지
- [x] 방탈출 경험 횟수
- [x] 선호하는 방탈출 장르
- [x] MBTI
- [x] 본인의 강점
- [x] 중요하게 여기는 방탈출 요소
- [x] 공포테마 포지션
- [x] 힌트 사용
- [x] 자물쇠 vs 장치
- [x] 활동성
- [x] 싫어하는 요소
- [x] 배경 색
- [x] 생성 중 Lottie
- [x] 생성 완료

<br>
