### ISSUE TITLE
✅ 프로필 생성 - 방탈출 경험 횟수 범위 입력 추가

### ISSUE THREAD

**Issue by moondev03** [Prography-RoomE/roome_aos#27]
### 💼 작업 설명

방탈출 프로필 생성을 위한 정보 수집 플로우 단계 중 **방탈출 경험 횟수 범위 입력**기능을 추가
<br>

### ✅ To-do

- [x] 저장된 프로필 정보 조회 API 응답 수정
- [x] 선택지 제공을 위한 데이터 조회 API 수정
- [x] 범위 저장 API 추가

<br>
