### ISSUE TITLE
✅ 1차 QA 반영

### ISSUE THREAD

**Issue by moondev03** [Prography-RoomE/roome_aos#33]
### 💼 작업 설명

1차 QA 반영
- 프로필 생성 이어하기 다이얼로그 라이팅 및 버튼 색 수정
- 프로필 생성 중 방탈출 경험 횟수 Soft Keyboard 처리
- 프로필 생성 중 사용된 버튼들 그림자 제거
- 토스트 메시지 FadeIn/FadeOut Animation 제거
- 프로필 1:1 정방형 라이팅 추가
- 프로필 3:4 세로형 이미지에서 라이팅 수정
- 체크박스 터치 영역 텍스트까지 늘리기
<br>

### ✅ To-do

- [x] 프로필 생성 이어하기 다이얼로그 라이팅 및 버튼 색 수정
- [x] 프로필 생성 중 방탈출 경험 횟수 Soft Keyboard 처리
- [x] 프로필 생성 중 사용된 버튼들 그림자 제거
- [ ] 토스트 메시지 FadeIn/FadeOut Animation 제거
- [x] 프로필 1:1 정방형 라이팅 추가
- [x] 프로필 3:4 세로형 이미지에서 라이팅 수정
- [x] 체크박스 터치 영역 텍스트까지 늘리기
<br>
