### ISSUE TITLE
✅ 비공개 테스트 전 QA 반영

### ISSUE THREAD

**Issue by moondev03** [Prography-RoomE/roome_aos#53]
### 💼 작업 설명

비공개 테스트 전 진행한 QA 반영
<br>

### ✅ To-do

**바텀 네비게이션**

- [x]  바텀 네비게이션 폰트 적용 안됨
- [ ]  프로필 화면 chip shadow 수정해보기
- [x]  프로필 화면 [프로필 색상] chip 검정색일 때 표시 문제
<br>

**프로필 화면**

- [x]  프로필 화면 MBTI “NONE” → “-” 표기 변경
- [x]  프로필 생성 완료 시 프로필 화면으로 가도록 수정
<br>

**프로필 생성 - 카운트**

- [x]  하단 버튼 수정
- [x]  “번” 텍스트 뒤로 포커스 넘어가지 안도록 수정
- [x]  “다음” 버튼 비활성 상태일 때 #646464 적용
- [x]  “범위 선택”, “직접 입력” 버튼 다시 선택 시 checked 효과 없어짐
- [x]  “범위 선택” defalut는 “선택” 텍스트가 나오도록 수
- [x]  “직접 선택”에서 0을 지우고 다음 버튼 누를 시 앱 종료
<br>

**프로필 생성 - MBTI**

- [x]  프로필 생성 중 MBTI 화면 [프로필에 추가하지 않을래요] 선택 중일 때 Chip 클릭 시 해제 되도록 수정
<br>

**프로필 생성 - Color**

- [x]  프로필 생성 중 색상 선택 화면에서 chip storke 추가 (4px / white a32)
<br>

**프로필 생성 - Profile Generate**

- [x]  프로필 생성 중 완료 화면 “저장하기” → “이미지 저장하기”로 수정
- [x]  권한 요청 다이얼로그 수
<br>

**카카오 공유**

- [x]  카카오 공유 시 내 프로필인지 체크하는 대신 [로그인 중+회원가입 완료 상태]라면 “내 프로필로 이동”으로 표기
<br>

**회원가입**

- [x]  회원가입 약관 동의 페이지 동의 상태일 때 웹뷰에서 “동의” 버튼 누르면 동의 취소됨
- [x]  닉네임 페이지 진입 시 default로 focus 상태
<br>

**회원탈퇴**

- [x]  회원탈퇴 플로우 중 [기타] 터치 후 [텍스트 박스] 선택 후 뒤로가기 화살표 혹은 뒤로 갔다가 다시 기타 선택 후 텍스트 박스를 누르면 앱이 종료
<br>

**슬로건 변경**

- [x]  슬로건 이미지 변경
<br>
